default: &default
  adapter: postgresql
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: back_chalenge_development

test:
  <<: *default
  database: back_chalenge_test

production:
  primary:
    <<: *default
    database: back_chalenge_production
  cache:
    <<: *default
    database: chalenge_production_cache
    migrations_paths: db/cache_migrate